### ISSUE TITLE
Documentation.

### ISSUE THREAD

**Issue by EfrataAron** [Sanskriti1102/Techtalksintelligenz#107]
i want to improve the readme file to make it more lively.

**Comment by NITYANIT** [comment]
can you assign me this issue.i have worked on this before and im a beginner.

**Comment by Krishi1211** [comment]
@EfrataAron What changes would you make?

**Comment by EfrataAron** [comment]
@Krishi1211 i want to include real time update of contributors to the repo.

**Comment by Krishi1211** [comment]
Thats not required @EfrataAron
