### ISSUE TITLE
Fixing the alignment of footer

### ISSUE THREAD

**Issue by khwa04** [Sanskriti1102/Techtalksintelligenz#111]
I want to correct the spacing in footer that is fix the alignment of "Links" column in the footer.
![image](https://github.com/user-attachments/assets/f031bfdc-09b0-45d1-823c-8d3129e5d5bc)
Please assign this issue to me under GSSoC extnd and Hacktoberfest.

**Comment by Krishi1211** [comment]
What exactly would you change @khwa04

**Comment by khwa04** [comment]
I wish to shift the "Links" section towards right so that all columns are equi-spaced.
