### ISSUE TITLE
Improving design of language Selector

### ISSUE THREAD

**Issue by IkkiOcean** [Sanskriti1102/Techtalksintelligenz#113]
The current language selector lacks modern design and doesnt match the UI
Current state:

<img width="215" alt="Screenshot 2024-10-21 at 2 48 10 AM" src="https://github.com/user-attachments/assets/de87d591-12cd-4720-800f-40730f82f6a1">

this doesnt match with the UI therefore I want to make it look like this:

<img width="150" alt="Screenshot 2024-10-20 at 3 26 59 PM" src="https://github.com/user-attachments/assets/2d5b0a74-3ea5-4f28-890a-8a7cdb114de1">

**Comment by Krishi1211** [comment]
@IkkiOcean assigned
