### ISSUE TITLE
#can add a section called Tech Skill Assessments and Certification

### ISSUE THREAD

**Issue by SanikaBhalerao1345** [Sanskriti1102/Techtalksintelligenz#145]
can add certification section in navbar that is linked and which consist of course or mini-assessments on tech topics related to domains mentioned on website( like cyber-security, AI, nature inspired computing, intelligence security system etc) 
![image](https://github.com/user-attachments/assets/2255126e-b98c-4183-a2e4-f7674f71df68)

**Comment by SanikaBhalerao1345** [comment]
@Sanskriti1102 pls check my pr

**Comment by Sanskriti1102** [comment]
@SanikaBhalerao1345 done

**Comment by Sanskriti1102** [comment]
hence closing this issue
