### ISSUE TITLE
hey i saw a issue when you hover on dropdown it show list to far and when not hover it gone

### ISSUE THREAD

**Issue by viveksarkar0** [Sanskriti1102/Techtalksintelligenz#16]
hey i find this issue when user is not hovering it gone and it to far let me fix this for you assing me this issue under gssoc and hacktober fest 
<img width="1470" alt="Screenshot 2024-10-05 at 4 09 47 PM" src="https://github.com/user-attachments/assets/78ff5e98-29a7-4e19-a8fc-d8803ce4f460">

**Comment by Sanskriti1102** [comment]
this is not our website so closed this issue
