### ISSUE TITLE
Addition of All Contributors Photos in Readme | Readme Updation

### ISSUE THREAD

**Issue by Shariq2003** [Sanskriti1102/Techtalksintelligenz#17]
We can add all the contributor's photos in Readme file as a token of appreciation for their work.

Please assign this to me.

![image](https://github.com/user-attachments/assets/24846984-f3d2-44a4-8d2b-2a5025d1ceb9)
Like this

**Comment by Sanskriti1102** [comment]
@Shariq2003 assigned

**Comment by Shariq2003** [comment]
> @Shariq2003 assigned

Got it, will raise a pr within 1 hr

**Comment by Shariq2003** [comment]
@Sanskriti1102 please review and merge

**Comment by Sanskriti1102** [comment]
@Shariq2003 assigned

**Comment by Shariq2003** [comment]
> @Shariq2003 assigned

@Sanskriti1102 mam, i have raised the PR, please check

**Comment by Sanskriti1102** [comment]
@Shariq2003 can u send me the PR's link ?

**Comment by Shariq2003** [comment]
@Sanskriti1102 mam, actually @Krishi1211 closed my PR as completed, because someone else raise the PR that is accepted.
Even though I was assigned yesterday, and that one raises a PR by today, still the PR got accepted.
