### ISSUE TITLE
Create a button to switch light and dark mode

### ISSUE THREAD

**Issue by shreyad2806** [Sanskriti1102/Techtalksintelligenz#2]
I can add a button in the right corner for switching the color mode.I can implement a dark mode toggle with smooth transitions between light and dark themes. 
Please assign me this issue under gssoc'24 EXTENDED and hacktoberfest.

**Comment by Janhavi078** [comment]
i want to add toggle button that can do smooth transition from light to dark assign this issue to me under gsssoc ext and hacktoberfest @Sanskriti1102

**Comment by Sanskriti1102** [comment]
@shreyad2806 make a complete responsive website in light mode as well

**Comment by Sanskriti1102** [comment]
@shreyad2806 what's the status of this issue?

**Comment by shreyad2806** [comment]
Almost done will submit it before 12pm tomorrow.

**Comment by Sanskriti1102** [comment]
@shreyad2806 can u raise the PR for the same, coz the deadline which you had set has passed !

**Comment by toufiqfarhan0** [comment]
I would like to work on this @Sanskriti1102

**Comment by coder-writes** [comment]
@Sanskriti1102 I would l like to work on the issue and will also resolve the whole problem by tomorrow,  I will add a toggle button in the website to switch to dark and light mode and will also make the UI work in both cases smoothly.

**Comment by Sanskriti1102** [comment]
@coder-writes you can make a new issue on this combined one and will assign you the same !

**Comment by Krishi1211** [comment]
Closing the issue since a new one is created
