### ISSUE TITLE
Add Contributing.md File 

### ISSUE THREAD

**Issue by rajatsinghal02** [Sanskriti1102/Techtalksintelligenz#22]
I want to create a contributing.md file to the repositories so that contributor's can easily understand how to make a issue and how to make a pull Requests.
@Sanskriti1102 please assign this issue to me.

**Comment by Sanskriti1102** [comment]
@rajatsinghal02 assigned

**Comment by AnujSaha0111** [comment]
Can you please assign it to me? I want to work on it.
