### ISSUE TITLE
Changing the twitter logo to X logo in the contact us section

### ISSUE THREAD

**Issue by tarunkumar2005** [Sanskriti1102/Techtalksintelligenz#24]
![image](https://github.com/user-attachments/assets/564f68ca-598c-413c-ba86-c4b42da3bca3)

Changing the twitter logo to X logo in the contact us section

@Sanskriti1102 @Krishi1211 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on fixing this issue the other issue is related to footer only i will fix the logo on contact us section

**Comment by tarunkumar2005** [comment]
@Sanskriti1102 Can you assign this to me it is in the contact us section not in footer.

**Comment by Krishi1211** [comment]
twitter icon needs to be changed in footer and we feature on section can you do both?

**Comment by tarunkumar2005** [comment]
Okay will do in footer and in we feature both

**Comment by tarunkumar2005** [comment]
@Krishi1211 assign this to me
