### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by Meetjain1** [Sanskriti1102/Techtalksintelligenz#32]
Dear Project Admin @Sanskriti1102 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by Sanskriti1102** [comment]
All the labels are been added as per the rules and since my project isn't under hacktoberst so it's label isn't there

**Comment by Sanskriti1102** [comment]
My project was accepted a bit late in gssoc extended

**Comment by Meetjain1** [comment]
@Sanskriti1102 For hacktoberfest you dont have to register anywhere, PAs only need to add Hacktoberfest topic in their repository.
And since gssoc projects are part of hacktoberfest I request you to add hacktoberfest accepted label.

**Comment by Sanskriti1102** [comment]
@Meetjain1 okay will do it right now itself, i didn't know this fact !

**Comment by Meetjain1** [comment]
> @Meetjain1 okay will do it right now itself, i didn't know this fact ! In hacktoberfest may i know how the label should look like?

Thankyou for your understanding . @Sanskriti1102 

label for hacktoberfest is 

"hacktoberfest-accepted"

**Comment by Sanskriti1102** [comment]
@Meetjain1 i have added all the labels even have applied those on pr's which are closed and also on issues

**Comment by Meetjain1** [comment]
> @Meetjain1 i have added all the labels even have applied those on pr's which are closed and also on issues

Thankyou @Sanskriti1102 !
