### ISSUE TITLE
Responsive issue in mobile view

### ISSUE THREAD

**Issue by Rahul7raj** [Sanskriti1102/Techtalksintelligenz#4]
# Issue
- Currently, the UI is not responsive in mobile view.

## Recording
https://github.com/user-attachments/assets/d61298fc-d28a-4444-ab0d-64628d541654

## Proposed solution
I can fix the responsive issue on the mobile view.

@Sanskriti1102 Please assign this issue to me under GSSoC'24 EXTENDED and Hacktoberfest program.

**Comment by Rahul7raj** [comment]
@Sanskriti1102 please add gssoc-ext and hacktoberfest labels

**Comment by Sanskriti1102** [comment]
@Rahul7raj  this project is only under gssoc-ext and not on hacktoberfest label

**Comment by Sanskriti1102** [comment]
Also check the updated redme file of this repository @Rahul7raj
