### ISSUE TITLE
adding icons in footer (github)

### ISSUE THREAD

**Issue by devxMani** [Sanskriti1102/Techtalksintelligenz#44]
add gsoc ext and hacktoberfest label to it

**Comment by Krishi1211** [comment]
Which section of the footer you are talking about @devxMani ?

**Comment by devxMani** [comment]
![image](https://github.com/user-attachments/assets/c8e1b368-afc2-48bf-8c4f-89baa8178246)
this section for navigation to the repo if anyone wants to see the code...

**Comment by Sanskriti1102** [comment]
@devxMani currently this isn't required, hence closing the issue
