### ISSUE TITLE
adding CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by devxMani** [Sanskriti1102/Techtalksintelligenz#45]
have the guidelines for contributors
add gsoc ext and hacktoberfest labels

**Comment by Krishi1211** [comment]
assigned @devxMani

**Comment by Anuraj-IND** [comment]
has he done something yet on it? if not lemme do it

**Comment by Sanskriti1102** [comment]
@Anuraj-IND @devxMani has also raised the PR for the same, you can create some another issue for our project, hence closing this issue !

**Comment by Anuraj-IND** [comment]
I created issue coz ig I didn't saw a issue in this one coz no one put direct pull requests
