### ISSUE TITLE
BUG: In Join the Podcast

### ISSUE THREAD

**Issue by Abhi9shinde** [Sanskriti1102/Techtalksintelligenz#53]
As you can see when hovered over the button its not readable whole button becomes blue.
I can fix that issue.
Please assign me this issue and I'll start working on it right away

![Screenshot 2024-10-09 171443](https://github.com/user-attachments/assets/c5b350e3-c0df-4970-ada8-8b5c42991fac)

**Comment by Sanskriti1102** [comment]
@Abhi9shinde this issue has already been addressed by someone who had earlier created a similar PR, hence closing the issue.
