### ISSUE TITLE
set up backend and create an api for contact form 

### ISSUE THREAD

**Issue by AyushSharma72** [Sanskriti1102/Techtalksintelligenz#65]
some one is building a contact form  https://github.com/Sanskriti1102/Techtalksintelligenz/issues/64
 i want to set up backend and add an Api  so that you can receive the message of the people filling the form 

i will use nodejs to setup backend and nodemailer for creating api

please assign this issue to me @Sanskriti1102

**Comment by Krishi1211** [comment]
Can you implement these too Mail the responses to our email and store in a google sheet?

**Comment by AyushSharma72** [comment]
> Can you implement these too Mail the responses to our email and store in a google sheet?

Yes I can do it but hen make the issue level3

**Comment by Krishi1211** [comment]
We cant assign this as level3 it will be level 2 issue

**Comment by AyushSharma72** [comment]
> We cant assign this as level3 it will be level 2 issue

You don't have any backend I have to set it up that an overhead that's why

**Comment by Krishi1211** [comment]
@AyushSharma72 assigned
