### ISSUE TITLE
Redesign "We Feature On" Section

### ISSUE THREAD

**Issue by AsmitaMishra24** [Sanskriti1102/Techtalksintelligenz#67]
The "We Feature On" section needs improvements to feel modern and engaging. Key issues identified:
-  Design: The section looks plain, and the visual experience is not appealing.
- Hover Effects: Existing card or logo hover effects are basic and do not enhance user engagement.

**Present:**
![Screenshot 2024-10-12 203518](https://github.com/user-attachments/assets/e9cfa12e-83ff-43da-9c07-681cf9c72e9b)

**Suggestion:**
https://github.com/user-attachments/assets/83b3d553-dcbc-4872-b73d-50383c18ee74

**Comment by Krishi1211** [comment]
@AsmitaMishra24 assigned

**Comment by arduvey29** [comment]
@Krishi1211 I would love to contribute in this task.
