### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website. (WEBSITE)

### ISSUE THREAD

**Issue by tarunkumar2005** [Sanskriti1102/Techtalksintelligenz#68]
Adding the contributors page to mention all the awersome people who have contributed to the website. (WEBSITE)

@Sanskriti1102 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by Krishi1211** [comment]
Currently not looking for this feature will definitely consider in the future
