### ISSUE TITLE
Fix Contact Us Section Links 

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Sanskriti1102/Techtalksintelligenz#71]
The links in the Contact Us section are not working correctly. Clicking on images like YouTube does not redirect to the intended pages. Propose fixing the broken links to ensure they function properly.

![image](https://github.com/user-attachments/assets/6b892d72-5415-455c-a06d-8a309c50c846)

**Comment by AnushkaChouhan25** [comment]
Can you please assign me this issue under gssoc-extd and hactoberfest-accepted with suitable level label, I want to contirbute in it.

**Comment by Krishi1211** [comment]
@AnushkaChouhan25 assigned
