### ISSUE TITLE
improving scroll bar to match sites UI

### ISSUE THREAD

**Issue by Sourabh782** [Sanskriti1102/Techtalksintelligenz#73]
Changing scrollbar design so it could match sites UI
![image](https://github.com/user-attachments/assets/00cff142-02f0-4937-8e54-a9a9c52a55a9)

**Comment by KRITHIYA** [comment]
I can resolve this issue

**Comment by Sourabh782** [comment]
> I can resolve this issue

Hello krithiya, but I raised the issue, so if @Sanskriti1102 finds it well, so it would be assigned to me first
