### ISSUE TITLE
[Bug] Last Header links is hidden with 'JOIN THE PODCAST' button

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Sanskriti1102/Techtalksintelligenz#75]
### Description :
the link in  header is hidden with 'JOIN THE PODCAST' button

### Type of change : 
- bug fix

### Screenshots : 
![Screenshot from 2024-10-14 20-53-52](https://github.com/user-attachments/assets/8f022b2b-8b96-4446-b330-753db6a286cc)

### Expected Criteria : 
all links should be displaying properly

**Comment by Saurabhchaudhary9799** [comment]
hey @Sanskriti1102 , could you please assign this to me ?

**Comment by KRITHIYA** [comment]
I can resolve this issue
