### ISSUE TITLE
Django?|login|sign in|user authorisation

### ISSUE THREAD

**Issue by Anuraj-IND** [Sanskriti1102/Techtalksintelligenz#76]
why this project doesnt have a proper backend frame work i mean it does says it has django in its tag but it doesnt also login sign in feature nor do it has any dbms like sql or mongo db , i can make proper backend with login sigin feature and it can store data of it in sql datasheet which can be used as pleased also i saw someone did some backend work with node.js if things go well we both will work together for api funtionality also it doesnt have any logout feature idk why plus there should be a contact form a small contact form with basic data like ph number mail message that we can store in contact form through django not to mention there will be another form for login and sign functionality with sessions, i have does these stuffs i can drop the code if i cant work on it these codes might help others to create a proper backend , since this website dont have any proper framework itll take a bit of time but itll look good after that from behind too not so messy
![login-django1](https://github.com/user-attachments/assets/28c5d0f5-65a1-445c-8c65-85720d2d8b68)

![logout-django](https://github.com/user-attachments/assets/9bd92883-44f1-4dce-b89b-c9753a0e1f92)

![login-django](https://github.com/user-attachments/assets/05adf669-68bf-473c-b3f0-2be62cee56d4)

**Comment by Krishi1211** [comment]
Hii @Anuraj-IND currently we havenodejs backend for the contact form

**Comment by Krishi1211** [comment]
Than you @Anuraj-IND
