### ISSUE TITLE
Designing Custom error 404 page

### ISSUE THREAD

**Issue by dev129** [Sanskriti1102/Techtalksintelligenz#77]
#### Description
The current 404 error page does not provide an optimal user experience, especially in a production environment. A well-designed custom 404 page can enhance the overall aesthetic and usability of the site.

#### Proposed Solution
I propose to design a custom 404 error page that aligns with the site's branding and improves user engagement. 

#### Plan
1. **Labeling**: Please assign the issue the `GSSOC-ext` and `Hacktoberfest` and `level` labels.
2. **Wireframe**: I will share a wireframe within the first hour of being assigned to the issue.
3. **Approval**: Upon receiving approval for the wireframe, I will start the design process.
4. **Completion**: The design will be completed within 24 hours of wireframe approval.

#### Benefits
- Improved user experience and site navigation.
- Enhanced branding consistency.
- Potential reduction in bounce rates.

I look forward to your feedback and hope to contribute positively to the project!

**Comment by Krishi1211** [comment]
@dev129 assigned

**Comment by dev129** [comment]
Thanks, but before that do you have some design in your mind, like how should it look like ? according to you

**Comment by dev129** [comment]
Just let me know before i start drawing wireframe

**Comment by Krishi1211** [comment]
@dev129 you can refer #7 for templates

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/079d57f8-17a5-4655-8614-ffb7b307a586)
This will be the wireframe of the design, after your approval shall i start the design, if you need any other changes then let me know

**Comment by Krishi1211** [comment]
Works @dev129

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/2c078f7c-389a-442b-a0c5-d236faf0a8b6)
Hey @Krishi1211, I have just designed the page and here is the first design, is there anything you would like to add or subtract ?

**Comment by Krishi1211** [comment]
Can We add the original Navbar?

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/dc126a51-f263-4d39-98b5-719cdeb22f89)
Did the whole page

**Comment by Krishi1211** [comment]
Well Done @dev129 you can create a PR

**Comment by Krishi1211** [comment]
merged
