### ISSUE TITLE
fix ui bug

### ISSUE THREAD

**Issue by aditya07389** [Sanskriti1102/Techtalksintelligenz#83]
hey i just noticed "join podcast" is over lapping with a part of navbar 

![image](https://github.com/user-attachments/assets/5ad59445-19e9-497f-a0a6-d4b88c81b088)

i could fix this 

Assign this to me under gssoc extd and hacktoberfest

Thankyou !!

**Comment by Krishi1211** [comment]
It is already been addressed @aditya07389
