### ISSUE TITLE
Enhance the 'stats' section in the website

### ISSUE THREAD

**Issue by swathivemula7** [Sanskriti1102/Techtalksintelligenz#85]
1)   I would like to add a dynamic counting animation for the numbers in the below shown section, starting from 0 and counting up to their final values over a few seconds. This would enhance the user interaction.

2)  Also I would like to well align it properly, since it is not well aligned.

![Capturedfjrnf](https://github.com/user-attachments/assets/47fc9f25-d613-4740-9e5a-9e931fcd6feb)

@Sanskriti1102  Kindly assign me this issue under the gssoc and hacktoberfest labels.

**Comment by Krishi1211** [comment]
@swathivemula7 assigned

**Comment by swathivemula7** [comment]
@Krishi1211 Since the dynamic counting animation is live on the website, can i work on aligning the stats section.

**Comment by Krishi1211** [comment]
@swathivemula7 please add dynamic counting as well

**Comment by swathivemula7** [comment]
> @swathivemula7 please add dynamic counting as well

@Krishi1211 in the stats section, the numbers are being counted from 0 and this feature was already there,please refer the video linked in pull request...are you talking about that feature...

**Comment by Krishi1211** [comment]
Nope I was talking about getting live views and likes @swathivemula7

**Comment by Krishi1211** [comment]
Is that possible?

**Comment by swathivemula7** [comment]
I don't have a clear idea on that.. @Krishi1211

**Comment by swathivemula7** [comment]
@Krishi1211 I have updated the PR by adding the correct stats by reviewing your YouTube channel...so kindly consider..
