### ISSUE TITLE
Modify Background Video Playback to Pause on Last Frame

### ISSUE THREAD

**Issue by IkkiOcean** [Sanskriti1102/Techtalksintelligenz#93]
#### Description
The background video on the homepage is intended to welcome users when they first visit the site. Currently, the video loops after it finishes playing, which disrupts the user experience. We need to modify this functionality so that the video pauses on the last frame instead of looping.

#### Steps to Reproduce
1. Open the homepage of the application in a web browser.
2. Observe the background video playback when the page loads.
3. Notice that the video continues in a loop after it finishes playing.

#### Expected Behavior
- The background video should play automatically when the homepage loads.
- Once the video reaches the end, it should **pause** on the last frame instead of hiding.
- Users should remain engaged with the final scene of the video, enhancing their welcoming experience.

https://github.com/user-attachments/assets/8cccbe6f-e9eb-4bf5-8f0e-ab4af1b8fa30

**Comment by Krishi1211** [comment]
@IkkiOcean assigned
