### ISSUE TITLE
Adding multi language support system✨

### ISSUE THREAD

**Issue by T-Rahul-prabhu-38** [Sanskriti1102/Techtalksintelligenz#98]
I want to add multi language support system to the website which can help us understand in their native language.
@Sanskriti1102 can you assign me this issue.

**Comment by Sanskriti1102** [comment]
@T-Rahul-prabhu-38 this issue has already been addressed earlier and merged it's PR, do raise an issue which isn't addressed earlier. Hence closing this issue
